{
  "name": "amber-atelier-api",
  "type": "web",
  "env": "node",
  "buildCommand": "npm install",
  "startCommand": "npm start",
  "rootDir": "server-starter",
  "envVars": [
    {
      "key": "NODE_ENV",
      "value": "production"
    },
    {
      "key": "PORT",
      "value": "5000"
    }
  ]
}
